### ISSUE TITLE
error: default argument given for parameter 4 of 'void SCD30_Modbus::scd30Write

### ISSUE THREAD

**Issue by max5555** [Robertndrei/SCD30-Modbus#2]
Compilation error in Plarformio at scd30_modbus.cpp:68:70

`void SCD30_Modbus::scd30Write(uint8_t func, uint16_t cmd, uint16_t data, 
                              uint8_t addr = SCD30_MODBUSADDR_DEFAULT) {
`

**Comment by max5555** [comment]
It is ok without default parameter:

```
void SCD30_Modbus::scd30Write(uint8_t func, uint16_t cmd, uint16_t data, uint8_t addr) {
```

**Comment by Robertndrei** [comment]
I'm not getting that error. Can you tell me wich version of Platformio are you using?.
I'm building with version 5.2.3 for platform atmelmegaavr with no issues.

**Comment by SboleWork** [comment]
Hi, I'm having that same issue. I'm on Core 6.0.2 and Home 3.4.2. I'm getting the following error.
`lib/SCD30-Modbus/src/scd30_modbus.cpp:68:113: error: default argument given for parameter 4 of 'void SCD30_Modbus::scd30Write(uint8_t, uint16_t, uint16_t, uint8_t)' [-fpermissive]
 void SCD30_Modbus::scd30Write(uint8_t func, uint16_t cmd, uint16_t data, uint8_t addr = SCD30_MODBUSADDR_DEFAULT) {
                                                                                                                 ^
In file included from lib/SCD30-Modbus/src/scd30_modbus.cpp:1:
lib/SCD30-Modbus/src/scd30_modbus.h:40:12: note: previous specification in 'void SCD30_Modbus::scd30Write(uint8_t, uint16_t, uint16_t, uint8_t)' here
       void scd30Write(uint8_t func, uint16_t cmd, uint16_t data, uint8_t addr = SCD30_MODBUSADDR_DEFAULT);
            ^~~~~~~~~~
*** [.pio\build\esp32cam\lib757\SCD30-Modbus\scd30_modbus.cpp.o] Error 1`


Max555's suggestion (deleting " = SCD30_MODBUSADDR_DEFAULT") worked for me.
